apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx-proxy
          image: lo20hyy7.kr.private-ncr.ntruss.com/myproject-nginx
          ports:
            - containerPort: 3010
            - containerPort: 3020
            - containerPort: 8010
            - containerPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: web3010
      protocol: TCP
      port: 3010
      targetPort: 3010
    - name: web3020
      protocol: TCP
      port: 3020
      targetPort: 3020
    - name: api8010
      protocol: TCP
      port: 8010
      targetPort: 8010
    - name: api8020
      protocol: TCP
      port: 8020
      targetPort: 8020
